services:

  postgres:
    image: postgres:16

    container_name: duty_postgres

    restart: always

    environment:
      POSTGRES_DB: duty_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:

    build:
      context: ./backend

    container_name: duty_backend

    restart: always

    depends_on:
      - postgres

    ports:
     - "8081:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/duty_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

  frontend:

    build:
      context: ./frontend

    container_name: duty_frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  postgres_data: